### PR TITLE
fix: fixes #9

### LINKED ISSUE #9: TypeError: Cannot read properties of undefined (reading 'range')
Hi, I got the following exception when linting my react/typescript project:

```tsx
pnpm eslint --ext .ts,.tsx .

Oops! Something went wrong! :(

ESLint: 8.56.0

TypeError: Cannot read properties of undefined (reading 'range')
Occurred while linting /Users/chenyuwang/pawpawmall/packages/store/src/routes/_root.my-page.mail-settings.tsx:167
Rule: "svg-jsx/camel-case-dash"
    at Object.replaceText (/Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/rule-fixer.js:95:50)
    at Object.fix (/Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint-plugin-svg-jsx@1.2.2/node_modules/eslint-plugin-svg-jsx/rules/camel-case-dash.js:61:29)
    at normalizeFixes (/Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/report-translator.js:194:28)
    at /Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/report-translator.js:365:49
    at Object.report (/Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:1047:41)
    at validateAndFixProp (/Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint-plugin-svg-jsx@1.2.2/node_modules/eslint-plugin-svg-jsx/rules/camel-case-dash.js:51:23)
    at /Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint-plugin-svg-jsx@1.2.2/node_modules/eslint-plugin-svg-jsx/rules/camel-case-dash.js:79:13
    at Array.forEach (<anonymous>)
    at handleSpreadOperator (/Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint-plugin-svg-jsx@1.2.2/node_modules/eslint-plugin-svg-jsx/rules/camel-case-dash.js:74:17)
    at /Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint-plugin-svg-jsx@1.2.2/node_modules/eslint-plugin-svg-jsx/rules/camel-case-dash.js:94:15
```

The code to lint is:

```tsx
<MyPageForm
  {...emailForm.bindForm({
    async onSubmit(body) {},
  })}
>
  {...}
</MyPageForm>
```

Although I'm not quite understanding this library, the problem seems to be that `nodeToFix` is possibly undefined.

```js
        function handleSpreadOperator(attr, charDelimtiter) {
          const props = getPropsFromObjectString(getPropIdentifier(attr, context))
          props.forEach((prop) => {
            const nodeToFix = attr?.argument?.properties?.find((node) => {
              return node?.key?.value === prop
            })?.key

            validateAndFixProp(prop, nodeToFix, charDelimtiter)
          })
        }
```

### PR DESCRIPTION
**Pull request by hanayashiki**

### CODE REVIEW

**Comment by fostimus** [comment]
Let me try to reproduce this, but if what you are suggesting fixes the issue, I think adding a null check to [this line](https://github.com/fostimus/eslint-plugin-svg-jsx/blob/0f163ed5868d197c83b3eef62112a65837a28a74/rules/camel-case-dash.js#L60) is better so any time the `validateAndFixProp` function is called, it will handle the undefined case. Thanks for opening a PR!

**Comment by hanayashiki** [comment]
> Let me try to reproduce this, but if what you are suggesting fixes the issue, I think adding a null check to [this line](https://github.com/fostimus/eslint-plugin-svg-jsx/blob/0f163ed5868d197c83b3eef62112a65837a28a74/rules/camel-case-dash.js#L60) is better so any time the `validateAndFixProp` function is called, it will handle the undefined case. Thanks for opening a PR!

I think we should not pass any non-null node to `validateAndFixProp`. Handling only valid input makes the function simpler.

**Comment by fostimus** [comment]
> I think we should not pass any non-null node to `validateAndFixProp`. Handling only valid input makes the function simpler.

It makes the function simpler, but it keeps the bug in the codebase for anyone who uses that function. You could write a null check at the top of `validateAndFixProp` to ensure `nodeToFix` is not null, and it would still be as simple. It would also be more apparent to other developers what will happen if `nodeToFix` is null.

**Comment by hanayashiki** [comment]
> > I think we should not pass any non-null node to `validateAndFixProp`. Handling only valid input makes the function simpler.
> 
> It makes the function simpler, but it keeps the bug in the codebase for anyone who uses that function. You could write a null check at the top of `validateAndFixProp` to ensure `nodeToFix` is not null, and it would still be as simple. It would also be more apparent to other developers what will happen if `nodeToFix` is null.

I can't agree with you. If that line should be changed, then we should replace every occurrence of  similar lines:
image

I think the discussion is based on untyped javascript, but there is indeed types in the developers' mind about the shape of input and non-nullabilities. Inability to handle unexpected null or shapes is not considered a bug.

**Comment by fostimus** [comment]
> I can't agree with you. If that line should be changed, then we should replace every occurrence of similar lines:

You're right, we should replace every occurrence of those lines. What we really _should_ do is simplify the logic of each of those functions into smaller functions that we can reuse throughout the project. But I wrote this plugin as a side project, and didn't have time to write it the correct way - there's a lot of copy/paste going on between each rule.

> Inability to handle unexpected null or shapes is not considered a bug.

From a technical perspective, sure. But if a user (in this case, you) runs your linter and this plugin breaks on a piece of code that has nothing to do with this plugin, it's a bug. This plugin is not behaving in the way it is 1) intended and 2) the user expects.

I'll approve your pull request so you can move forward with whatever else you're working on - but if you want to help with the maintainability of this project, handling the null case within the function will make for a more resilient plugin.

**Review by fostimus — APPROVED** [review]

**Comment by micha7a** [comment]
What happened to this PR? I just tried using this plugin for the first time and encountered the same error, also in the code that shouldn't have anything to do with this plugin, would be great if it could be fixed

**Comment by fostimus** [comment]
~~Released a fix in `1.2.3` that won't break for this case. It returns with a confusing eslint error, but at least for now linting won't break~~

`1.2.4` is the version you want, won't break and won't give you a random eslint error

**Pull request merged**
